# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 230, 691, 311))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.list2 = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.list2.setObjectName("list2")
        self.gridLayout.addWidget(self.list2, 0, 4, 1, 1)
        self.list1 = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.list1.setFlow(QtWidgets.QListView.TopToBottom)
        self.list1.setLayoutMode(QtWidgets.QListView.Batched)
        self.list1.setObjectName("list1")
        self.gridLayout.addWidget(self.list1, 0, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 40, 691, 141))
        self.graphicsView.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 109, 691, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.b3.setObjectName("b3")
        self.horizontalLayout.addWidget(self.b3)
        self.b4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.b4.setObjectName("b4")
        self.horizontalLayout.addWidget(self.b4)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 691, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bowlcount = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.bowlcount.setObjectName("bowlcount")
        self.gridLayout_2.addWidget(self.bowlcount, 0, 1, 1, 1)
        self.alrcount = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.alrcount.setObjectName("alrcount")
        self.gridLayout_2.addWidget(self.alrcount, 0, 3, 1, 1)
        self.wicketcount = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.wicketcount.setObjectName("wicketcount")
        self.gridLayout_2.addWidget(self.wicketcount, 0, 2, 1, 1)
        self.batcount = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.batcount.setObjectName("batcount")
        self.gridLayout_2.addWidget(self.batcount, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 210, 91, 16))
        self.label_2.setObjectName("label_2")
        self.points_available = QtWidgets.QLabel(self.centralwidget)
        self.points_available.setGeometry(QtCore.QRect(110, 210, 55, 16))
        self.points_available.setObjectName("points_available")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(430, 210, 71, 16))
        self.label_8.setObjectName("label_8")
        self.points_used = QtWidgets.QLabel(self.centralwidget)
        self.points_used.setGeometry(QtCore.QRect(500, 210, 55, 16))
        self.points_used.setObjectName("points_used")
        self.team_name = QtWidgets.QLabel(self.centralwidget)
        self.team_name.setGeometry(QtCore.QRect(160, 0, 401, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.team_name.setFont(font)
        self.team_name.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.team_name.setAlignment(QtCore.Qt.AlignCenter)
        self.team_name.setObjectName("team_name")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 26))
        self.menubar.setObjectName("menubar")
        self.menu_Manage_Team = QtWidgets.QMenu(self.menubar)
        self.menu_Manage_Team.setObjectName("menu_Manage_Team")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Team = QtWidgets.QAction(MainWindow)
        self.actionNew_Team.setObjectName("actionNew_Team")
        self.actionOpen_Team = QtWidgets.QAction(MainWindow)
        self.actionOpen_Team.setObjectName("actionOpen_Team")
        self.actionSave_Team = QtWidgets.QAction(MainWindow)
        self.actionSave_Team.setObjectName("actionSave_Team")
        self.actionEvaluate_Team = QtWidgets.QAction(MainWindow)
        self.actionEvaluate_Team.setObjectName("actionEvaluate_Team")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu_Manage_Team.addAction(self.actionNew_Team)
        self.menu_Manage_Team.addSeparator()
        self.menu_Manage_Team.addAction(self.actionOpen_Team)
        self.menu_Manage_Team.addSeparator()
        self.menu_Manage_Team.addAction(self.actionSave_Team)
        self.menu_Manage_Team.addSeparator()
        self.menu_Manage_Team.addAction(self.actionEvaluate_Team)
        self.menu_Manage_Team.addSeparator()
        self.menu_Manage_Team.addAction(self.actionExit)
        self.menu_Manage_Team.addSeparator()
        self.menubar.addAction(self.menu_Manage_Team.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", ">"))
        self.b1.setText(_translate("MainWindow", "BAT"))
        self.b2.setText(_translate("MainWindow", "BOW"))
        self.b3.setText(_translate("MainWindow", "AR"))
        self.b4.setText(_translate("MainWindow", "WK"))
        self.bowlcount.setText(_translate("MainWindow", "Bowlers(Bow)  ##"))
        self.alrcount.setText(_translate("MainWindow", "Allrounders(AR) ##"))
        self.wicketcount.setText(_translate("MainWindow", "WicketKeeper(WK)  ##"))
        self.batcount.setText(_translate("MainWindow", "Batsmen(Bat)  ##"))
        self.label_2.setText(_translate("MainWindow", "Point Available"))
        self.points_available.setText(_translate("MainWindow", "####"))
        self.label_8.setText(_translate("MainWindow", "Point used"))
        self.points_used.setText(_translate("MainWindow", "####"))
        self.team_name.setText(_translate("MainWindow", " TEAM NAME "))
        self.menu_Manage_Team.setTitle(_translate("MainWindow", "    Manage Team"))
        self.actionNew_Team.setText(_translate("MainWindow", "New Team"))
        self.actionOpen_Team.setText(_translate("MainWindow", "Open Team"))
        self.actionSave_Team.setText(_translate("MainWindow", "Save Team"))
        self.actionEvaluate_Team.setText(_translate("MainWindow", "Evaluate Team"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
